name: project deploy

on: push

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Deployment event triggering through HTTP request
        run: curl http://45.33.75.143:1234/update?branch=${GITHUB_REF##*/}